apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigatway
  labels:
    app: api-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: amarcs721992/amarcs721992/api-gateway:latest
        command: ["/bin/sh"]
        args: ["-c", "sleep 10000 && echo Sleep expired > /dev/termination-log"]
        ports:
        - containerPort: 80
 