server:
  port: 1111
spring:
  cloud:
     gateway:
      discovery :
       locator:
        enabled: true
      routes:         
      - id: user-management
        uri: http://localhost:2222/
        predicates:
        - Path=/user-management/** 
        
      - id: common-service
        uri: http://localhost:3333/
        predicates:
        - Path=/common/**
     